name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_call:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
        node:
          - 18
          - 20
          - 22
      fail-fast: false
    name: Testing Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - run: npm install
      - run: npm run build_x64
      - run: npm run build_arm64
      - run: npm test

      - uses: actions/upload-artifact@v4
        if: github.ref_type == 'tag' && matrix.node == 20
        with:
          path: prebuilds/**
          name: prebuilds-${{matrix.os}}
          retention-days: 2
