name: Publish

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    uses: "./.github/workflows/ci.yml"

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Download prebuilds
        uses: actions/download-artifact@v4
        with:
          path: prebuilds
          pattern: prebuilds-*
          merge-multiple: true

      - name: List prebuilds
        run: tree prebuilds

      - name: Install dependencies
        run: npm install

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create release
        run: |-
          gh release create --generate-notes \
            ${{ github.ref_name }} \
            prebuilds/**/*.node
        env:
          GH_TOKEN: ${{ github.token }}
